### ISSUE TITLE
System.Windows.Forms breaks .NET 6 project

### ISSUE THREAD

**Issue by ivanzanolla** [nhibernate/NHibernate.Mapping.Attributes#16]
Hello there!

Unfortunately there is a System.Windows.Forms reference in the library, this reference doesn't permit to use NHibernate engine. The exception is the following

`Message	"Unable to load one or more of the requested types.\r\nCould not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)"	string`

Is there some solution? I built a Web Api in .NET 6, .netstandard2.0 to bridge .NET 4.8 where there is the NHibernate engine. Everything works, except the load of the library.

Thanks

**Comment by hazzik** [comment]
Hi @ivanzanolla, NHibernate.Mapping.Attributes assembly itself does not include the `System.Windows.Forms` reference and is actually a .NET Standard/.NET 4.6.1 library. There is a generator, which has the reference to `System.Windows.Forms`, but it should not be referenced to your project.

**Comment by ivanzanolla** [comment]
> Hi @ivanzanolla, NHibernate.Mapping.Attributes assembly itself does not include the `System.Windows.Forms` reference and is actually a .NET Standard/.NET 4.6.1 library. There is a generator, which has the reference to `System.Windows.Forms`, but it should not be referenced to your project.

Apoligize, I downloaded your code and run it into my application I found out System.Windows.Forms are inside my application code!
